#!/usr/bin/env python3
"""Snapshot a deployed portal's human review state to a local JSON file.

Why this exists rather than a volume snapshot: Northflank's volume backup API is
gated (`403 Feature disabled for your account` on this plan), so
`northflank_deploy.py backup` cannot run here. This is the fallback that works
today, and it backs up the part that is genuinely irreplaceable.

`push_corpus` can always rebuild the *documents* from the local corpus, but it
cannot rebuild review state: the remote upload route inserts every row with
``status='pending'``, so re-uploading resets every section and carries no
annotations. Reviewer work is the portal's actual output and nothing else in the
repo preserves it.

What lands in the snapshot, per document, is whatever
``GET /api/documents/{id}/export?format=json`` returns -- per-section
``review_status``, annotations, footnotes, and the completion summary. Detector
``findings`` are not included; those are machine output and are regenerated by a
re-sync.

There is no import route yet, so this preserves the data rather than offering a
one-click restore. Writing the importer is a separate job; having the JSON is what
makes it possible at all.

Only the standard library is used, matching `northflank_deploy.py`, so CI needs
nothing but the interpreter.

Usage:
    python tools/snapshot_review.py --base-url https://your-portal.example.com
    python tools/snapshot_review.py --base-url ... --out data/backups
"""

from __future__ import annotations

import argparse
import http.client
import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "data" / "backups"
TIMEOUT = 120
MAX_ATTEMPTS = 4

# The API runs one uvicorn worker on a small compute plan. Under that starvation it both
# 502s and truncates responses mid-stream (IncompleteRead), so a single-shot fetch loses
# documents that are perfectly readable a second later. Observed, not hypothetical.
TRANSIENT = (
    urllib.error.URLError,
    http.client.HTTPException,
    json.JSONDecodeError,
    TimeoutError,
    ConnectionError,
)


class SnapshotError(RuntimeError):
    """A document could not be fetched after retries."""


def fetch_json(url: str) -> object:
    last: Exception | None = None
    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            request = urllib.request.Request(url, headers={"Accept": "application/json"})
            with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
                return json.loads(response.read().decode("utf-8"))
        except TRANSIENT as exc:
            last = exc
            if attempt < MAX_ATTEMPTS:
                time.sleep(2**attempt)
    raise SnapshotError(f"{MAX_ATTEMPTS} attempts failed: {getattr(last, 'reason', last)}")


def snapshot(base_url: str, out_dir: Path) -> Path:
    base = base_url.rstrip("/")
    documents = fetch_json(f"{base}/api/documents")
    if not isinstance(documents, list):
        raise SystemExit(f"error: {base}/api/documents did not return a list")
    if not documents:
        raise SystemExit(
            f"error: {base} reports an empty corpus -- refusing to write an empty "
            "snapshot over a good one"
        )

    print(f"{len(documents)} documents to snapshot", flush=True)
    exports: list[dict] = []
    failed: list[tuple[str, str]] = []

    for index, doc in enumerate(documents, start=1):
        doc_id = doc.get("id", "")
        name = doc.get("name", doc_id)
        url = f"{base}/api/documents/{urllib.parse.quote(doc_id)}/export?format=json"
        try:
            payload = fetch_json(url)
        except SnapshotError as exc:
            # Keep going: a partial snapshot of 87 documents beats no snapshot, and the
            # summary below makes the gap explicit rather than silent.
            print(f"  [{index}/{len(documents)}] FAILED {name}: {exc}", flush=True)
            failed.append((name, str(exc)))
            continue
        exports.append({"id": doc_id, "name": name, "export": payload})
        print(f"  [{index}/{len(documents)}] {name}", flush=True)

    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"review-snapshot-{stamp}.json"
    path.write_text(
        json.dumps(
            {
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "base_url": base,
                "document_count": len(exports),
                "failed": [{"name": n, "reason": r} for n, r in failed],
                "documents": exports,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    size_mb = path.stat().st_size / 1048576
    print(f"Wrote {path} ({size_mb:.1f} MB, {len(exports)} documents)", flush=True)
    if failed:
        print(f"warning: {len(failed)} document(s) missing from this snapshot", flush=True)
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--base-url", required=True, help="Deployed portal base URL")
    parser.add_argument(
        "--out",
        default=str(DEFAULT_OUT),
        help=f"Directory to write the snapshot into (default {DEFAULT_OUT})",
    )
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    snapshot(args.base_url, Path(args.out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
